### ISSUE TITLE
camel-salesforce-kafka-connector missing dependency library

### ISSUE THREAD

**Issue by yingbo-wu** [apache/camel-kafka-connector#1114]
The camel-salesforce-kafka-connector-0.8.0-package.tar.gz missing jetty-http-9.4.36.v20210114.jar

**Comment by sintezcs** [comment]
Any updates on this issue? Camel-salesforce-kafka-connector **is completely broken**. I use it with the official Confluent Platform Kafka Connect Docker image (https://hub.docker.com/r/confluentinc/cp-kafka-connect-base). The connector doesn't work at all, without downloading the jetty-http jar. I can confirm that it is reproducible for all versions starting from 0.7.0 (I tried 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.9.0). 

Without downloading the jar, the connector starts but doesn't process any messages and there are no errors in the output. Enabling the DEBUG logging for `org.eclipse.jetty.client` package uncovers the errors that are happening silently: 
```
java.lang.LinkageError: loader constraint violation: when resolving method 'void org.eclipse.jetty.http.GZIPContentDecoder.<init>(org.eclipse.jetty.io.ByteBufferPool, int)'
 the class loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @1dd6d4b7 of the current class, 
org/eclipse/jetty/client/GZIPContentDecoder, and the class loader 'app' for the method's defining class, 
org/eclipse/jetty/http/GZIPContentDecoder, have different Class objects for the type 
org/eclipse/jetty/io/ByteBufferPool used in the signature (org.eclipse.jetty.client.GZIPContentDecoder is in 
unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @1dd6d4b7, parent 
loader org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader @62e7f11d; 
org.eclipse.jetty.http.GZIPContentDecoder is in unnamed module of loader 'app')

kafka-connect-salesforce-source_1  | 	at org.eclipse.jetty.client.GZIPContentDecoder.<init>(GZIPContentDecoder.java:44)
kafka-connect-salesforce-source_1  | 	at org.eclipse.jetty.client.GZIPContentDecoder$Factory.newContentDecoder(GZIPContentDecoder.java:87)
kafka-connect-salesforce-source_1  | 	at org.eclipse.jetty.client.HttpReceiver.responseHeaders(HttpReceiver.java:311)
kafka-connect-salesforce-source_1  | 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.headerComplete(HttpReceiverOverHTTP.java:310)
kafka-connect-salesforce-source_1  | 	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1213)
kafka-connect-salesforce-source_1  | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1503)
kafka-connect-salesforce-source_1  | 	... 20 more
```

**Comment by oscerd** [comment]
As a workaround you can add the jar of jetty into your connector folder for salesforce.

**Comment by oscerd** [comment]
If you have a ready PR please open it.

**Comment by sintezcs** [comment]
> As a workaround you can add the jar of jetty into your connector folder for salesforce.

yeah, this is how I do it now. Looks like the issue was introduced with this commit: https://github.com/orpiske/camel-kafka-connector/commit/1ccb1ce73d1b1e27d475bfba1b281042665f7a5f

There is a chance, that the current issue only happens when you use Confluent's docker image. (otherwise, I don't have an idea how the connector can be broken for such a long period of time).
So, currently, I'm not sure about the best way to fix this.

**Comment by oscerd** [comment]
We have an integration tests for salesforce using pure Kafka connect and we didn't catch any problem. Do you happen to know what is the jetty version used by Confluent's docker image?

**Comment by orpiske** [comment]
> We have an integration tests for salesforce using pure Kafka connect and we didn't catch any problem. Do you happen to know what is the jetty version used by Confluent's docker image?

The latest image from confluent seems to be using `jetty-http-9.4.38.v20210224.jar` in their cp-kafka container.

**Comment by orpiske** [comment]
BTW, the offending commit references issue #407, but it is actually issue #807 that was fixed by it (and that seems to have caused this).

**Comment by orpiske** [comment]
@valdar @oscerd given the original issue was a conflict between the jetty from Salesforce and the one from Kafka, I believe we can try removing that exclusion. Versions from each of them seem quite close.

**Comment by oscerd** [comment]
We can try, but don't trust Jetty too much :-)

**Comment by valdar** [comment]
@sintezcs can you try with this connector https://www.dropbox.com/s/spi8abb2n039840/camel-salesforce-kafka-connector-0.11.0-SNAPSHOT-package.tar.gz?dl=0 to see if the issue is still present?

**Comment by kidpollo** [comment]
@valdar still broken I noticed the jetty versions dont match the error I have is silent was only able to access enabling debug logs but the connector never reports problems 

```
 org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: bad response on HttpConnectionOverHTTP@6f359c5::DecryptedEndPoint@1412451a{l=/100.117.59.97:50548,r=login.salesforce.com/13.108.235.130:443,OPEN,fill=-,flush=-,to=307/10000}
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.badMessage(HttpReceiverOverHTTP.java:391)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.http.HttpParser.badMessage(HttpParser.java:1647)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1634)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:204)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:144)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:169)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at java.base/java.lang.Thread.run(Thread.java:829)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server Caused by: org.eclipse.jetty.http.BadMessageException: 400: Bad Response
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	... 21 more
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'void org.eclipse.jetty.http.GZIPContentDecoder.<init>(org.eclipse.jetty.io.ByteBufferPool, int)' the class loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @c3972d0 of the current class, org/eclipse/jetty/client/GZIPContentDecoder, and the class loader 'app' for the method's defining class, org/eclipse/jetty/http/GZIPContentDecoder, have different Class objects for the type org/eclipse/jetty/io/ByteBufferPool used in the signature (org.eclipse.jetty.client.GZIPContentDecoder is in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @c3972d0, parent loader org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader @5f9b2141; org.eclipse.jetty.http.GZIPContentDecoder is in unnamed module of loader 'app')
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.GZIPContentDecoder.<init>(GZIPContentDecoder.java:44)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.GZIPContentDecoder$Factory.newContentDecoder(GZIPContentDecoder.java:87)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.HttpReceiver.responseHeaders(HttpReceiver.java:311)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.headerComplete(HttpReceiverOverHTTP.java:310)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1232)
erc-streams-cp-kafka-connect-d4b59f4dc-jfhmr cp-kafka-connect-server 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1522)
```

**Comment by kidpollo** [comment]
Never mind ^ was on v 0.10. With your snapshot I get a different error now and does not silently fail. I'll investigate that separately.

**Comment by kidpollo** [comment]
Woop ! I can report confidently that this works now

**Comment by valdar** [comment]
Ok thanks, that should be shortlu released in version 0.10.1
